{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "84283477-e538-463e-b594-229afd94d406",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-02-27 13:17:30.606 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-27 13:17:30.984 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\olive\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2026-02-27 13:17:30.985 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-27 13:17:30.985 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-27 13:17:30.985 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-27 13:17:30.986 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-27 13:17:30.987 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-27 13:17:30.987 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-27 13:17:30.987 Session state does not function when running a script without `streamlit run`\n",
      "2026-02-27 13:17:30.988 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-27 13:17:30.989 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-27 13:17:30.989 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-27 13:17:30.990 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-27 13:17:30.990 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-27 13:17:30.991 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-27 13:17:30.992 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-27 13:17:30.992 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-27 13:17:30.993 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-27 13:17:30.995 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-27 13:17:30.995 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-27 13:17:30.996 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-27 13:17:30.996 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-27 13:17:30.997 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-27 13:17:30.997 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import yfinance as yf\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.preprocessing import MinMaxScaler\n",
    "from tensorflow.keras.models import Sequential\n",
    "from tensorflow.keras.layers import LSTM, Dense, Dropout\n",
    "from tensorflow.keras.callbacks import EarlyStopping\n",
    "from tensorflow.keras import regularizers\n",
    "from itertools import product\n",
    "import random\n",
    "import io\n",
    "import datetime\n",
    "\n",
    "st.title(\"📈 Stock LSTM Forecast & Backtest (Auto-update Latest Data)\")\n",
    "\n",
    "# 1️⃣ User inputs\n",
    "ticker_input = st.text_input(\"Enter stock ticker (e.g., 2330.TW):\", value=\"2330.TW\")\n",
    "date_input = st.date_input(\"Prediction start date (YYYY-MM-DD)\", value=datetime.date.today())\n",
    "\n",
    "if st.button(\"Start Prediction\"):\n",
    "\n",
    "    try:\n",
    "        ticker = ticker_input.strip()\n",
    "        input_date = pd.to_datetime(date_input)\n",
    "\n",
    "        # -------------------------------\n",
    "        # 2️⃣ Auto-download latest 2-year data\n",
    "        # -------------------------------\n",
    "        data = yf.download(ticker, period=\"2y\", interval=\"1d\")[['Close']].dropna()\n",
    "        data.index = pd.to_datetime(data.index)\n",
    "        if data.empty:\n",
    "            st.error(f\"No data found for {ticker}\")\n",
    "            st.stop()\n",
    "\n",
    "        # 如果輸入日期比最新交易日還晚，改成最新交易日\n",
    "        latest_date = data.index[-1]\n",
    "        if input_date > latest_date:\n",
    "            input_date = latest_date\n",
    "            st.warning(f\"Input date is after last trading day. Using latest trading day: {latest_date.date()}\")\n",
    "\n",
    "        # -------------------------------\n",
    "        # 3️⃣ Technical indicators\n",
    "        # -------------------------------\n",
    "        def RSI(series, period=14):\n",
    "            delta = series.diff()\n",
    "            gain = delta.where(delta>0, 0)\n",
    "            loss = -delta.where(delta<0, 0)\n",
    "            avg_gain = gain.rolling(period).mean()\n",
    "            avg_loss = loss.rolling(period).mean()\n",
    "            rs = avg_gain / avg_loss\n",
    "            return 100 - (100 / (1 + rs))\n",
    "\n",
    "        def MACD(series, fast=12, slow=26, signal=9):\n",
    "            ema_fast = series.ewm(span=fast, adjust=False).mean()\n",
    "            ema_slow = series.ewm(span=slow, adjust=False).mean()\n",
    "            macd = ema_fast - ema_slow\n",
    "            signal_line = macd.ewm(span=signal, adjust=False).mean()\n",
    "            return macd, signal_line\n",
    "\n",
    "        def Bollinger(series, period=20):\n",
    "            sma = series.rolling(period).mean()\n",
    "            std = series.rolling(period).std()\n",
    "            upper = sma + 2*std\n",
    "            lower = sma - 2*std\n",
    "            return upper, lower\n",
    "\n",
    "        data['RSI'] = RSI(data['Close'])\n",
    "        data['MACD'], data['MACD_signal'] = MACD(data['Close'])\n",
    "        data['BB_upper'], data['BB_lower'] = Bollinger(data['Close'])\n",
    "        data.dropna(inplace=True)\n",
    "\n",
    "        # -------------------------------\n",
    "        # 4️⃣ Weighted normalization\n",
    "        # -------------------------------\n",
    "        weights = 1 + 0.5 * np.arange(len(data)) / len(data)\n",
    "        data_weighted = data * weights[:, None]\n",
    "        scaler = MinMaxScaler()\n",
    "        scaled_data = scaler.fit_transform(data_weighted)\n",
    "\n",
    "        # -------------------------------\n",
    "        # 5️⃣ LSTM dataset\n",
    "        # -------------------------------\n",
    "        time_step = 60\n",
    "        def create_dataset(dataset, time_step=time_step):\n",
    "            X, Y = [], []\n",
    "            for i in range(time_step, len(dataset)):\n",
    "                X.append(dataset[i-time_step:i])\n",
    "                Y.append(dataset[i,0])\n",
    "            return np.array(X), np.array(Y)\n",
    "\n",
    "        X, y = create_dataset(scaled_data)\n",
    "\n",
    "        # -------------------------------\n",
    "        # 6️⃣ LSTM model auto neuron selection\n",
    "        # -------------------------------\n",
    "        lstm1_options = [100, 120, 150]\n",
    "        lstm2_options = [50, 80, 100]\n",
    "        best_val_loss = float(\"inf\")\n",
    "        best_model = None\n",
    "        early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)\n",
    "\n",
    "        for n1, n2 in product(lstm1_options, lstm2_options):\n",
    "            model = Sequential()\n",
    "            model.add(LSTM(n1, return_sequences=True, input_shape=(X.shape[1], X.shape[2]),\n",
    "                           kernel_regularizer=regularizers.l2(0.001)))\n",
    "            model.add(Dropout(0.3))\n",
    "            model.add(LSTM(n2, return_sequences=False, kernel_regularizer=regularizers.l2(0.001)))\n",
    "            model.add(Dropout(0.3))\n",
    "            model.add(Dense(30, kernel_regularizer=regularizers.l2(0.001)))\n",
    "            model.add(Dense(1))\n",
    "            model.compile(optimizer='adam', loss='mean_squared_error')\n",
    "            history = model.fit(X, y, batch_size=32, epochs=60, validation_split=0.1,\n",
    "                                callbacks=[early_stop], verbose=0)\n",
    "            val_loss = min(history.history['val_loss'])\n",
    "            if val_loss < best_val_loss:\n",
    "                best_val_loss = val_loss\n",
    "                best_model = model\n",
    "\n",
    "        st.success(f\"✅ Best model trained! Validation loss: {best_val_loss:.6f}\")\n",
    "\n",
    "        # -------------------------------\n",
    "        # 7️⃣ Predict next 30 days\n",
    "        # -------------------------------\n",
    "        start_idx = data.index.get_loc(input_date) - time_step\n",
    "        last_60_days = scaled_data[start_idx:data.index.get_loc(input_date)+1]\n",
    "        X_test = np.array([last_60_days])\n",
    "        future_days = 30\n",
    "        predicted_prices = []\n",
    "        current_input = X_test.copy()\n",
    "        for _ in range(future_days):\n",
    "            pred = best_model.predict(current_input)[0][0]\n",
    "            temp = np.tile(pred, (scaled_data.shape[1],))\n",
    "            pred_price = float(scaler.inverse_transform([temp])[0][0])\n",
    "            pred_price *= (1 + random.uniform(-0.03, 0.03))\n",
    "            predicted_prices.append(pred_price)\n",
    "            current_input = np.append(current_input[:,1:,:], [[temp]], axis=1)\n",
    "        predicted_prices = np.array(predicted_prices).flatten()\n",
    "        future_dates = pd.date_range(input_date + pd.Timedelta(days=1), periods=future_days, freq='B')\n",
    "        df_future = pd.DataFrame({\"Date\": future_dates, \"Predicted_Close\": predicted_prices})\n",
    "\n",
    "        # -------------------------------\n",
    "        # 8️⃣ Backtest historical data\n",
    "        # -------------------------------\n",
    "        X_test_seq, y_test_seq = create_dataset(scaled_data)\n",
    "        y_test_prices = data['Close'].values[time_step:]\n",
    "        y_pred_scaled = best_model.predict(X_test_seq)\n",
    "        y_pred_prices = []\n",
    "        for pred_scaled in y_pred_scaled:\n",
    "            temp = np.tile(pred_scaled, (scaled_data.shape[1],))\n",
    "            y_pred_prices.append(float(scaler.inverse_transform([temp])[0][0]))\n",
    "        y_pred_prices = np.array(y_pred_prices).flatten()\n",
    "\n",
    "        # -------------------------------\n",
    "        # 9️⃣ Simulated portfolio\n",
    "        # -------------------------------\n",
    "        initial_cash = 100000\n",
    "        cash = initial_cash\n",
    "        shares = 0\n",
    "        portfolio_value = []\n",
    "        for i in range(len(y_pred_prices)):\n",
    "            if i < len(y_pred_prices)-1:\n",
    "                if y_pred_prices[i+1] > y_pred_prices[i] and shares == 0:\n",
    "                    shares = cash / y_pred_prices[i]\n",
    "                    cash = 0\n",
    "                elif y_pred_prices[i+1] <= y_pred_prices[i] and shares > 0:\n",
    "                    cash = shares * y_pred_prices[i]\n",
    "                    shares = 0\n",
    "            total = cash + (shares * y_pred_prices[i] if shares > 0 else 0)\n",
    "            portfolio_value.append(total)\n",
    "        portfolio_value = np.array(portfolio_value).flatten()\n",
    "\n",
    "        # -------------------------------\n",
    "        # 10️⃣ CSV download buttons\n",
    "        # -------------------------------\n",
    "        csv_future = df_future.to_csv(index=False).encode('utf-8')\n",
    "        csv_backtest = pd.DataFrame({\n",
    "            \"Date\": data.index[-len(y_test_prices):],\n",
    "            \"Actual_Close\": y_test_prices.flatten(),\n",
    "            \"Predicted_Close\": y_pred_prices.flatten(),\n",
    "            \"Portfolio_Value\": portfolio_value\n",
    "        }).to_csv(index=False).encode('utf-8')\n",
    "\n",
    "        st.download_button(\n",
    "            label=\"📥 Download 30-Day Forecast CSV\",\n",
    "            data=csv_future,\n",
    "            file_name=f\"{ticker}_predicted_30_days.csv\",\n",
    "            mime=\"text/csv\"\n",
    "        )\n",
    "\n",
    "        st.download_button(\n",
    "            label=\"📥 Download Backtest CSV\",\n",
    "            data=csv_backtest,\n",
    "            file_name=f\"{ticker}_backtest.csv\",\n",
    "            mime=\"text/csv\"\n",
    "        )\n",
    "\n",
    "        # -------------------------------\n",
    "        # 11️⃣ Visualization\n",
    "        # -------------------------------\n",
    "        fig, ax1 = plt.subplots(figsize=(12,6))\n",
    "        ax2 = ax1.twinx()\n",
    "        ax1.plot(data.index[-60:], data['Close'].tail(60), label=\"Historical Close\", color='blue', linewidth=2)\n",
    "        ax1.plot(data.index[-len(y_pred_prices):], y_pred_prices, label=\"Model Prediction\", color='green', linewidth=2)\n",
    "        ax1.plot(future_dates, predicted_prices, marker='o', label=\"Next 30 Days Forecast\", color='red', linewidth=2)\n",
    "        ax2.plot(data.index[-len(y_pred_prices):], portfolio_value, color='orange', label=\"Simulated Portfolio Value\", linewidth=2)\n",
    "        ax1.set_xlabel(\"Date\")\n",
    "        ax1.set_ylabel(\"Stock Price (TWD)\")\n",
    "        ax2.set_ylabel(\"Portfolio Value (TWD)\")\n",
    "        lines, labels = ax1.get_legend_handles_labels()\n",
    "        lines2, labels2 = ax2.get_legend_handles_labels()\n",
    "        ax1.legend(lines + lines2, labels + labels2, loc='upper left')\n",
    "        ax1.tick_params(axis='x', rotation=45)\n",
    "        st.pyplot(fig)\n",
    "\n",
    "    except Exception as e:\n",
    "        st.error(f\"Error: {str(e)}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5348962f-9d5e-4347-8caa-95dfe53cb4d7",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
